#!/usr/bin/env bash
# Script to check subdomains 

domain=$1

function fnOutput() {
	for arg; do
		echo -n "The subdomain $arg is a "
		dig "$arg.$domain" | grep -A1 'ANSWER SECTION:' | tail -n1 |
                #awk '{print $4 " record and points to " $5}'
                awk '{printf("%s record and points to %s\n",$4,$5)}'
	done
}

if [ $# -eq 2 ]; then
	subdomain=$2
        if [ "$subdomain" = "www" ] || [ "$subdomain" = "lb-01" ] || [ "$subdomain" = "web-01" ] || [ "$subdomain" = "web-02" ];then
		echo -n "The subdomain $2 is a "
		dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | 
                #tail -n1 | awk '{print $4 " record and points to " $5}'
                tail -n1 | awk '{printf("%s record and points to %s\n",$4, $5)}'
	fi

else
	if [ $# -lt 1 -o $# -gt 2 ];then
		exit 99
	fi

		fnOutput 'www' 'lb-01' 'web-01' 'web-02'
fi
