#!/usr/bin/env bash
# copy a file remotely to a server
if [ "$#" -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 99;
fi
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
