#!/usr/bin/env bash
#Task 1 Install HAProxy with balance roundrobin to configure the load between two servers

sudo apt-get update
sudo apt-get -y install haproxy
sudo sed -i '$ a\\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1204-web-01 35.231.101.65:80\n\tserver 1204-web-02 3.87.83.183:80' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
