#!/usr/bin/env bash
#print FizzBuzz if mult 5 and 3 Fizz to mult3 and Buzz mult 5
for i in {1..100}; do
mod3=$((i%3))
mod5=$((i%5))
	if [ $mod3 == 0 ] && [ $mod5 == 0 ];then
		echo "FizzBuzz"
	elif [ $mod3 == 0 ]; then
		echo "Fizz"
	elif [ $mod5 == 0 ];then
		echo "Buzz"
	else
		echo $i
	fi
done
