#!/usr/bin/env bash
#script that loops from 1 to 10 and,displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration,displays Holberton School for the other iterations
i=1;
while [ $i -gt 0 -a $i -lt 11 ];do
	if [ $i -eq 4 ] ; then
		echo "bad luck";
		i=$((i+1));
		continue;
	fi
	if [ $i -eq 8 ] ; then
		echo "good luck";
		i=$((i+1));
		continue;
	fi
	echo "Holberton School";
i=$((i+1));
done
