#!/usr/bin/env bash
#Script that displays superstitius numbers from 1 to 20 and,
i=1;
while [ $i -gt 0 -a $i -lt 21 ];do
	case $i in
		5) echo "bad luck from China"
		echo $i
		;;
		10) echo "bad luck from Japan"
		echo $i
		;;
		18) echo "bad luck from Italy"
		echo $i
		;;
		*) echo $i;
		;;
	esac
i=$((i+1));
done
