#!/usr/bin/env bash
# Configures NGINX to run as user nginx instead of root

netstat -lpn | grep apache | awk -F' ' '{print $7}' | cut -d'/' -f1 | xargs kill
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/www-data;/nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
