#!/usr/bin/env bash
# Configures NGINX to run as user nginx instead of root

pkill nginx
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo sed -i 's/www-data;/nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
